name: 'Fume Deployment'
description: 'Deploy fume environments with Github Actions'
author: 'Kevin Olson <acidjazz@gmail.com>'
branding:
  icon: 'cloud-lightning'
  color: 'blue'
inputs:
  environment:
    description: 'Environment to deploy to'
    required: true
  token:
    description: 'Fume Token'
    required: true
  target:
    description: 'Target directory of lambda within repo'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Install Fume
      run: npm install -g fume-cli
      shell: bash
    - name: Deploy with Fume
      working-directory: ${{ inputs.target }}
      run: fume deploy ${{ inputs.environment }}
      env:
        FUME_TOKEN: ${{ inputs.token }}
      shell: bash
